function screenshots(){var fb='',R=' top: -1000px;',ob='" for "gwt:onLoadErrorFn"',mb='" for "gwt:onPropertyErrorFn"',$='");',pb='#',Sb='.cache.js',rb='/',xb='//',Lb='1E2020AD330274C7113690298E7C1371',Mb='3DF7C74668457E3AA8772C12B999B5A4',Nb='8623A11FDF7EF71684BEFE1E0246B5C6',Rb=':',gb='::',S='<html><head><\/head><body><\/body><\/html>',jb='=',qb='?',lb='Bad handler "',Y='Chrome',X='DOMContentLoaded',M='DUMMY',Ob='E20CC424493A63AECBBB5D075D2C350E',Pb='E9020CE054974BB2DA5DABCB56B56C7A',Qb='F1DB9B02BDA156432478C857C2C141FA',wb='base',ub='baseUrl',H='begin',N='body',G='bootstrap',tb='clear.cache.gif',ib='content',Zb='end',Z='eval("',Gb='gecko',Hb='gecko1_8',I='gwt.codesvr.screenshots=',J='gwt.codesvr=',Yb='gwt/standard/standard.css',nb='gwt:onLoadErrorFn',kb='gwt:onPropertyErrorFn',hb='gwt:property',bb='head',Wb='href',Fb='ie6',Eb='ie8',Db='ie9',O='iframe',sb='img',U='javascript',P='javascript:""',Tb='link',Xb='loadExternalRefs',cb='meta',ab='moduleRequested',_='moduleStartup',Cb='msie',db='name',zb='opera',Q='position:absolute; width:0; height:0; border:none; left: -1000px;',Ub='rel',Bb='safari',K='screenshots',Kb='screenshots.devmode.js',vb='screenshots.nocache.js',eb='screenshots::',T='script',Jb='selectingPermutation',L='startup',Vb='stylesheet',W='undefined',Ib='unknown',yb='user.agent',V='var $wnd = window.parent;',Ab='webkit';var o=window;var p=document;r(G,H);function q(){var a=o.location.search;return a.indexOf(I)!=-1||a.indexOf(J)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:K,sessionId:o.__gwtStatsSessionId,subSystem:L,evtGroup:a,millis:(new Date).getTime(),type:b})}}
screenshots.__sendStats=r;screenshots.__moduleName=K;screenshots.__errFn=null;screenshots.__moduleBase=M;screenshots.__softPermutationId=0;screenshots.__computePropValue=null;screenshots.__getPropMap=null;screenshots.__gwtInstallCode=function(){};screenshots.__gwtStartLoadingFragment=function(){return null};var s=function(){return false};var t=function(){return null};__propertyErrorFunction=null;var u=o.__gwt_activeModules=o.__gwt_activeModules||{};u[K]={moduleName:K};var v;function w(){y();return v}
function x(){y();return v.getElementsByTagName(N)[0]}
function y(){if(v){return}var a=p.createElement(O);a.src=P;a.id=K;a.style.cssText=Q+R;a.tabIndex=-1;p.body.appendChild(a);v=a.contentDocument;if(!v){v=a.contentWindow.document}v.open();v.write(S);v.close();var b=v.getElementsByTagName(N)[0];var c=v.createElement(T);c.language=U;var d=V;c.text=d;b.appendChild(c)}
function z(k){function l(a){function b(){if(typeof p.readyState==W){return typeof p.body!=W&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(X,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(X,d,false)}var e=setInterval(function(){if(b()){d()}},50)}
function m(c){function d(a,b){a.removeChild(b)}
var e=x();var f=w();var g;if(navigator.userAgent.indexOf(Y)>-1&&window.JSON){var h=f.createDocumentFragment();h.appendChild(f.createTextNode(Z));for(var i=0;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(f.createTextNode(j.substring(1,j.length-1)))}h.appendChild(f.createTextNode($));g=f.createElement(T);g.language=U;g.appendChild(h);e.appendChild(g);d(e,g)}else{for(var i=0;i<c.length;i++){g=f.createElement(T);g.language=U;g.text=c[i];e.appendChild(g);d(e,g)}}}
screenshots.onScriptDownloaded=function(a){l(function(){m(a)})};r(_,ab);var n=p.createElement(T);n.src=k;p.getElementsByTagName(bb)[0].appendChild(n)}
screenshots.__startLoadingFragment=function(a){return C(a)};screenshots.__installRunAsyncCode=function(a){var b=x();var c=w().createElement(T);c.language=U;c.text=a;b.appendChild(c);b.removeChild(c)};function A(){var c={};var d;var e;var f=p.getElementsByTagName(cb);for(var g=0,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(db),k;if(j){j=j.replace(eb,fb);if(j.indexOf(gb)>=0){continue}if(j==hb){k=i.getAttribute(ib);if(k){var l,m=k.indexOf(jb);if(m>=0){j=k.substring(0,m);l=k.substring(m+1)}else{j=k;l=fb}c[j]=l}}else if(j==kb){k=i.getAttribute(ib);if(k){try{d=eval(k)}catch(a){alert(lb+k+mb)}}}else if(j==nb){k=i.getAttribute(ib);if(k){try{e=eval(k)}catch(a){alert(lb+k+ob)}}}}}t=function(a){var b=c[a];return b==null?null:b};__propertyErrorFunction=d;screenshots.__errFn=e}
function B(){function e(a){var b=a.lastIndexOf(pb);if(b==-1){b=a.length}var c=a.indexOf(qb);if(c==-1){c=a.length}var d=a.lastIndexOf(rb,Math.min(c,b));return d>=0?a.substring(0,d+1):fb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(sb);b.src=a+tb;a=e(b.src)}return a}
function g(){var a=t(ub);if(a!=null){return a}return fb}
function h(){var a=p.getElementsByTagName(T);for(var b=0;b<a.length;++b){if(a[b].src.indexOf(vb)!=-1){return e(a[b].src)}}return fb}
function i(){var a=p.getElementsByTagName(wb);if(a.length>0){return a[a.length-1].href}return fb}
function j(){var a=p.location;return a.href==a.protocol+xb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==fb){k=h()}if(k==fb){k=i()}if(k==fb&&j()){k=e(p.location.href)}k=f(k);return k}
function C(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return screenshots.__moduleBase+a}
function D(){var f=[];var g;function h(a,b){var c=f;for(var d=0,e=a.length-1;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(__propertyErrorFunc){__propertyErrorFunc(a,d,b)}throw null}
j[yb]=function(){var b=navigator.userAgent.toLowerCase();var c=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(function(){return b.indexOf(zb)!=-1}())return zb;if(function(){return b.indexOf(Ab)!=-1}())return Bb;if(function(){return b.indexOf(Cb)!=-1&&p.documentMode>=9}())return Db;if(function(){return b.indexOf(Cb)!=-1&&p.documentMode>=8}())return Eb;if(function(){var a=/msie ([0-9]+)\.([0-9]+)/.exec(b);if(a&&a.length==3)return c(a)>=6000}())return Fb;if(function(){return b.indexOf(Gb)!=-1}())return Hb;return Ib};i[yb]={gecko1_8:0,ie6:1,ie8:2,ie9:3,opera:4,safari:5};s=function(a,b){return b in i[a]};screenshots.__getPropMap=function(){var a={};for(var b in i){a[b]=k(b)}return a};screenshots.__computePropValue=k;o.__gwt_activeModules[K].bindings=screenshots.__getPropMap;r(G,Jb);if(q()){return C(Kb)}var l;try{h([Hb],Lb);h([Eb],Mb);h([Db],Nb);h([Fb],Ob);h([zb],Pb);h([Bb],Qb);l=f[k(yb)];var m=l.indexOf(Rb);if(m!=-1){g=parseInt(l.substring(m+1),10);l=l.substring(0,m)}}catch(a){}screenshots.__softPermutationId=g;return C(l+Sb)}
function E(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=p.createElement(Tb);b.setAttribute(Ub,Vb);b.setAttribute(Wb,C(a));p.getElementsByTagName(bb)[0].appendChild(b);__gwt_stylesLoaded[a]=true}}
r(Xb,H);c(Yb);r(Xb,Zb)}
A();screenshots.__moduleBase=B();u[K].moduleBase=screenshots.__moduleBase;var F=D();E();r(G,Zb);z(F);return true}
screenshots.succeeded=screenshots();